image: bitwalker/alpine-elixir:1.5.1
pipelines:
  default:
    - step:
        caches:
          - deps
          - build
        script:
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix deps.compile --all
          - mix test
        services:
        - db

definitions:
  caches:
    deps: deps
    build: _build
  services:
    db:
      image: postgres:9.6-alpine
      environment:
        POSTGRES_PASSWORD: "demo"
        POSTGRES_USER: "demo"