pipelines:
  branches:
    master:
    - step:
        image: elixir:1.5
        caches:
          - deps
          - build
        script:
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - mix test
        services:
        - db
 
definitions:
  caches:
    deps: deps
    build: _build
  services:
    db:
      image: postgres:9.6-alpine
      environment:
        POSTGRES_PASSWORD: "demo"
        POSTGRES_USER: "demo"